/// Flutter icons CutomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CutomIcons
///      fonts:
///       - asset: fonts/CutomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CutomIcons {
  CutomIcons._();

  static const _kFontFam = 'CutomIcons';
  static const String _kFontPkg = null;

  static const IconData dashboard = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
